# Colocar ao nível do bloco server.
set $webp_suffix "";

if ($http_accept ~* "image/webp") {
    set $webp_suffix ".webp";
}

location ~* ^/uploads/.+\.(jpe?g|png|gif)$ {
    add_header Vary Accept;
    expires 1y;
    try_files $uri$webp_suffix $uri =404;
}

# Exemplo de limite de upload:
client_max_body_size 20m;
